import { Product, InvestmentProduct, AdPlan } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    sellerId: "seller1",
    name: "무선 이어폰 CP-Buds",
    description: "노이즈 캔슬링을 지원하는 무선 이어폰입니다.",
    category: "전자기기",
    priceKrw: 89000,
    thumbnailUrl: "/images/products/earbuds.jpg",
    imageUrls: ["/images/products/earbuds.jpg"],
    stock: 120,
    rating: 4.6,
    reviewCount: 32,
    chnRewardRate: 0.02,
    isAdBoosted: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p2",
    sellerId: "seller2",
    name: "CP 캠핑 감성 텀블러",
    description: "보온보냉이 되는 캠핑용 텀블러입니다.",
    category: "생활용품",
    priceKrw: 25000,
    thumbnailUrl: "/images/products/tumbler.jpg",
    imageUrls: ["/images/products/tumbler.jpg"],
    stock: 300,
    rating: 4.8,
    reviewCount: 51,
    chnRewardRate: 0.02,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p3",
    sellerId: "seller1",
    name: "CP 미니멀 백팩",
    description: "심플한 디자인의 데일리 백팩입니다.",
    category: "패션잡화",
    priceKrw: 59000,
    thumbnailUrl: "/images/products/backpack.jpg",
    imageUrls: ["/images/products/backpack.jpg"],
    stock: 80,
    rating: 4.4,
    reviewCount: 18,
    chnRewardRate: 0.03,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p4",
    sellerId: "seller2",
    name: "스마트워치 CP-Fit",
    description: "심박수와 걸음 수를 측정하는 스마트워치입니다.",
    category: "전자기기",
    priceKrw: 149000,
    thumbnailUrl: "/images/products/watch.jpg",
    imageUrls: ["/images/products/watch.jpg"],
    stock: 60,
    rating: 4.5,
    reviewCount: 27,
    chnRewardRate: 0.02,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p5",
    sellerId: "seller3",
    name: "CP 블루투스 스피커",
    description: "휴대하기 좋은 소형 블루투스 스피커입니다.",
    category: "전자기기",
    priceKrw: 45000,
    thumbnailUrl: "/images/products/speaker.jpg",
    imageUrls: ["/images/products/speaker.jpg"],
    stock: 150,
    rating: 4.3,
    reviewCount: 40,
    chnRewardRate: 0.02,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p6",
    sellerId: "seller2",
    name: "CP 홈 디퓨저 세트",
    description: "은은한 향이 오래가는 홈 디퓨저 세트입니다.",
    category: "생활용품",
    priceKrw: 32000,
    thumbnailUrl: "/images/products/diffuser.jpg",
    imageUrls: ["/images/products/diffuser.jpg"],
    stock: 200,
    rating: 4.7,
    reviewCount: 63,
    chnRewardRate: 0.02,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p7",
    sellerId: "seller3",
    name: "CP 스테인리스 텀블러 보틀",
    description: "가벼우면서 튼튼한 스테인리스 물병입니다.",
    category: "생활용품",
    priceKrw: 18000,
    thumbnailUrl: "/images/products/bottle.jpg",
    imageUrls: ["/images/products/bottle.jpg"],
    stock: 400,
    rating: 4.6,
    reviewCount: 88,
    chnRewardRate: 0.02,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p8",
    sellerId: "seller1",
    name: "CP 캐주얼 스니커즈",
    description: "데일리로 신기 좋은 캐주얼 스니커즈입니다.",
    category: "패션잡화",
    priceKrw: 79000,
    thumbnailUrl: "/images/products/sneakers.jpg",
    imageUrls: ["/images/products/sneakers.jpg"],
    stock: 90,
    rating: 4.5,
    reviewCount: 34,
    chnRewardRate: 0.03,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p9",
    sellerId: "seller3",
    name: "CP 울 니트 스웨터",
    description: "따뜻하고 부드러운 울 혼방 니트입니다.",
    category: "패션잡화",
    priceKrw: 65000,
    thumbnailUrl: "/images/products/sweater.jpg",
    imageUrls: ["/images/products/sweater.jpg"],
    stock: 70,
    rating: 4.4,
    reviewCount: 22,
    chnRewardRate: 0.03,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p10",
    sellerId: "seller2",
    name: "CP 수제 원두 선물세트",
    description: "직접 로스팅한 원두로 구성된 선물세트입니다.",
    category: "식품",
    priceKrw: 28000,
    thumbnailUrl: "/images/products/coffee.jpg",
    imageUrls: ["/images/products/coffee.jpg"],
    stock: 250,
    rating: 4.9,
    reviewCount: 102,
    chnRewardRate: 0.04,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p11",
    sellerId: "seller1",
    name: "CP 유기농 견과류 믹스",
    description: "매일 챙겨 먹기 좋은 유기농 견과류 모음입니다.",
    category: "식품",
    priceKrw: 21000,
    thumbnailUrl: "/images/products/nuts.jpg",
    imageUrls: ["/images/products/nuts.jpg"],
    stock: 300,
    rating: 4.6,
    reviewCount: 47,
    chnRewardRate: 0.03,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p12",
    sellerId: "seller3",
    name: "CP 미니 다육식물 세트",
    description: "책상 위를 꾸며줄 앙증맞은 다육식물 세트입니다.",
    category: "기타",
    priceKrw: 15000,
    thumbnailUrl: "/images/products/plant.jpg",
    imageUrls: ["/images/products/plant.jpg"],
    stock: 180,
    rating: 4.7,
    reviewCount: 29,
    chnRewardRate: 0.02,
    isAdBoosted: false,
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_INVESTMENT_PRODUCTS: InvestmentProduct[] = [
  { id: "inv1", name: "7일 단기 예치", lockupDays: 7, expectedYieldRate: 0.01, minAmountChn: 10 },
  { id: "inv2", name: "30일 표준 예치", lockupDays: 30, expectedYieldRate: 0.05, minAmountChn: 50 },
  { id: "inv3", name: "90일 장기 예치", lockupDays: 90, expectedYieldRate: 0.15, minAmountChn: 100 },
];

export const MOCK_AD_PLANS: AdPlan[] = [
  { id: "ad1", label: "3일 부스트", durationDays: 3, costChn: 30, exposureMultiplier: 1.5 },
  { id: "ad2", label: "7일 프리미엄", durationDays: 7, costChn: 60, exposureMultiplier: 2.0 },
];